events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('creation/', views.New_view, name='new'),
    path('<token>/modifier/', views.Change_view, name='change'),
    path('liste/', views.List_view, name='list'),
    path('<token>/', views.Detail_view, name='detail'),
    path('inscription/<token>/', views.Register_view, name='register'),
    path('inscription/<token>/<args>/', views.Register_view, name='register'),
    path('<token>/commentaire/', views.Comment_view, name="comment"),
    path('<token>/commentaire/edit/<int:comment_id>', views.Comment_Edit_view, name="edit"),
    path('<token>/commentaire/delete/<int:comment_id>', views.Delete_com_view, name="delete_com"),
    path('<token>/commentaire/like/<int:comment_id>', views.Like_com_view, name="like_com"),
    path('<token>/commentaire/dislike/<int:comment_id>', views.Dislike_com_view, name="dislike_com"),
    path('ajax/getsetevent/', views.getSetPos, name='setPos'),
    path('mes_event/<method>', views.my_event, name='my_event'),
    path('mes_event/all', views.my_event, name='my_event_vanilla'),
]

events/templates/events/change.html
{% extends "base.html" %}


{% block title %} {{ block.super }} - Modifier l'Evenement {% endblock %}

{% block content %}
    <section id="new_event">
        <div class="container">
            <div class="box">
                <div class="panel">
                    <h1>Modifier l'Evenement</h1>
                    <hr>
                    <form method="POST" action="{% url 'events:change' event.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <span class="input-group-text"><i class="fas fa-clipboard"></i></span>
                                </div>
                                {{ form.titre }}
                            </div>

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <span class="input-group-text"><i class="fas fa-file-alt"></i></span>
                                </div>
                                {{ form.description }}
                            </div>

                            <div class="input-group">
                                {% if form.date.errors %}
                                    {{ form.date.errors }} <!-- c'est le format pour faire apparaitre les messages d'erreur a voir si tu veux en faire afficher d'autres -->
                                {% endif %}
                                <div class="input-group-addon">
                                    <span class="input-group-text"><i class="fas fa-calendar"></i></span>
                                </div>
                                {{ form.date }}
                            </div>

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <span class="input-group-text"><i class="fas fa-map-marker"></i></span>
                                </div>
                                {{ form.adresse }}
                            </div>

                            <input type="submit" value="modifier" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

events/templates/events/detail.html
{% extends "base.html" %}

{% block title %} {{ block.super }} - Event {% endblock %}

{% block content %}
    {{ event.titre }}
    <!-- aucune idée de la mise en page vus que tu a tout changé mais toutes les données sont dans event -->
    <a href="{% url 'events:change' event.id %}">Modifier</a>
{% endblock content %}

events/templates/events/detail_author.html
{% extends "base.html" %}

{% load static %}
{% load events_extras %}

{% block title %} {{ block.super }} - Event Auteur {% endblock %}

{% block content %}
    {{ event.title }}
    <input type="hidden" id="event_token" name="variable" value="{{ event.token }}">
    <!-- aucune idée de la mise en page vus que tu a tout changé mais toutes les données sont la -->
    <a href="{% url 'events:change' event.token %}">Modifier</a>

    <h4>Inscrit</h4>
    {% for inscrit in inscrits %}
        <p>{{ inscrit.last_name }}</p>
    {% endfor %}

    <h4>Commentaire</h4>
    {% for comment in comments %}
        {% if comment.response_to == None %}
            <p>posté le {{ comment.date }}</p>
            {% if comment.delete != True %}
                <p id="{{ comment.id }}">{{ comment.core }}</p>
                {% if comment.author == request.user %}
                    <button class="edite" value="{{ comment.id }}">Edite</button>
                {% endif %}
                <button class="answer" value="{{ comment.id }}">Répondre</button>
            {% else %}
                <p>Message Supprimé</p>
            {% endif %}
        {% else %}
            <p>posté le {{ comment.date }}</p>
            {% if comment.delete != True %}
                <p id="{{ comment.id }}">{{ comment.core }}</p>
                <p>Response to: {{ comment.response_to }}</p>
                {% if comment.author == request.user %}
                    <button class="edite" value="{{ comment.id }}">Edite</button>
                {% endif %}
            {% else %}
                <p>Message Supprimé</p>
            {% endif %}
        {% endif %}
        {% with 'events.delete_comment_'|addstr:comment.id as perm %}
            {% if perm in perms and comment.deleted != True %}
                <a href="{% url 'events:delete_com' event.token comment.id %}">Supprimer</a> 
            {% endif %}
        {% endwith %}
        <a href="{% url 'events:like_com' event.token comment.id %} ">+{{ comment.like }}</a> | <a href="{% url 'events:dislike_com' event.token comment.id %}">-{{ comment.dislike }}</a>        
    {% endfor %}
    <div>
        <form method="POST" action="{% url 'events:comment' event.token %}">
            {% csrf_token %}
            <label>Message
            {{ form.core }}
            </label>
            <input type="submit" value="envoyer"/>
        </form>
    </div>
{% endblock content %}

{% block script %}
    <script>
        var SCRF_TOKEN = '{{ csrf_token }}';
    </script>
    <script type="text/javascript" src="{% static 'js/comment_event.js' %}"></script>
{% endblock script %}

events/templates/events/inscription_user.html
{% extends "base.html" %}

{% block title %} {{ block.super }} - Event Public {% endblock %}

{% block content %}
    <p>Vous allez partager vos infrmation avec l'organisateur de l'evenement, êtes-vous sur?</p>
    <a href="{% url 'events:inscription' event.token 'accept' %}">Validez l'inscription</a>
    <br>
    <a href="{% url 'events:detail' event.token %}">Annuler</a>

{% endblock content %}

events/templates/events/list.html
{% extends "base.html" %}

{% load static %}

{% block title %} {{ block.super }} - Event {% endblock %}

{% block css %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin=""/>
{% endblock css %}

{% block js %}
<script src="https://unpkg.com/leaflet@1.3.3/dist/leaflet.js" integrity="sha512-tAGcCfR4Sc5ZP5ZoVz0quoZDYX5aCtEm/eu1KhSLj2c9eFrylXZknQYmxUssFaVJKvvc0dJQixhGjG2yXWiV9Q==" crossorigin=""></script>
<script type="text/javascript" src="{% static 'js/map_event.js' %}"></script>
{% endblock js %}

{% block content %}
	{% for event in events %}
		<p>
			{{ event.title }}
			{{ event.date }}
			{{ event.description }}
			<a href="{% url 'events:detail' event.token %}">Voir</a>
		</p>
	{% endfor %}

	<div id="mapid" style="height: 500px;"></div>
{% endblock content %}

events/templates/events/my_event.html
{% extends "members/account.html" %}


{% block title %} {{ block.super }} - Liste des evenements {% endblock %}

{% block account %}
    {% for event in events %}
        {{ event.title }}
        <a href="{% url 'events:detail' event.token %}">Voir</a>
    {% endfor %}
{% endblock account %}

events/templates/events/new.html
{% extends "members/account.html" %}

{% load static %}

{% block title %} {{ block.super }} - Nouvel évènement {% endblock title %}
{% block page_name %}new-event{% endblock page_name %}

{% block css %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin=""/>
{% endblock css %}

{% block js %}
<script src="https://unpkg.com/leaflet@1.3.3/dist/leaflet.js" integrity="sha512-tAGcCfR4Sc5ZP5ZoVz0quoZDYX5aCtEm/eu1KhSLj2c9eFrylXZknQYmxUssFaVJKvvc0dJQixhGjG2yXWiV9Q==" crossorigin=""></script>
<script type="text/javascript" src="{% static 'events/js/events.js' %}"></script>
{% endblock js %}

{% block account %}
<h1 class="title">Nouvel évènement</h1>
<hr>
<form method="POST" action="{% url 'events:new' %}">
	{% csrf_token %}
	<div id="newEvent-steps" class="steps">
		
		<!-- ITEMS -->
		<div class="step-item is-link">
			<div class="step-marker">
				<span class="icon">
					<i class="fas fa-info"></i>
				</span>
			</div>
			<div class="step-details">
				<p class="step-title">Étape 1</p>
				<p>Personnalisez votre événement</p>
			</div>
		</div>
		<div class="step-item is-link">
			<div class="step-marker">
				<span class="icon">
					<i class="fas fa-map-marker-alt"></i>
				</span>
			</div>
			<div class="step-details">
				<p class="step-title">Étape 2</p>
				<p>Choisissez l'adresse</p>
			</div>
		</div>
		<div class="step-item is-link">
			<div class="step-marker">
				<span class="icon">
					<i class="fas fa-user-friends"></i>
				</span>
			</div>
			<div class="step-details">
				<p class="step-title">Étape 3</p>
				<p>Invitez vos amis</p>
			</div>
		</div>
		<div class="step-item is-success">
			<div class="step-marker">
				<span class="icon">
					<i class="fas fa-flag"></i>
				</span>
			</div>
			<div class="step-details">
				<p class="step-title">Étape 4</p>
				<p>Finalisez votre événement</p>
			</div>
		</div>

		<!-- CONTENT -->
		<div class="steps-content">
			
			<!-- INFORMATIONS -->
			<div class="step-content">
				<div class="columns">
					<!-- IMAGE -->
					<div class="column is-one-third">
						<figure class="image is-square has-margin-bottom">
							<img id="preview" src="https://bulma.io/images/placeholders/480x480.png" alt="preview">
						</figure>
						<div class="file is-fullwidth is-link has-name">
							<label class="file-label">
								<input class="file-input" type="file" name="image">
								<span class="file-cta">
									<span class="file-icon">
										<i class="fas fa-upload"></i>
									</span>
									<span class="file-label">
										Choisissez une image...
									</span>
								</span>
								<span class="file-name">
									Aucun fichier
								</span>
							</label>
						</div>
					</div>
					<!-- INFOS -->
					<div class="column">
						<!-- TITLE -->
						<div class="field">
							<div class="control has-icons-left">
								{{ form.title }}
								<span class="icon is-small is-left">
									<i class="fas fa-clipboard"></i>
								</span>
							</div>
						</div>
						<!-- DESCRIPTION -->
						<div class="field">
							<div class="control">
								{{ form.description }}
							</div>
						</div>
						<!-- DATE -->
						<div class="field">
							{% if form.date.errors %}
								{{ form.date.errors }}
							{% endif %}
							<div class="control has-icons-left">
								{{ form.date }}
								<span class="icon is-small is-left">
									<i class="fas fa-calendar"></i>
								</span>
							</div>
						</div>

						<div class="field">
							{% for radio in form.nature %}
							{{ radio.tag }}
							<label for="{{ radio.id_for_label }}">{{ radio.choice_label }}</label>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>

			<!-- ADRESSE -->
			<div class="step-content">
				<div class="columns">
					<div class="column is-half">
						<!-- ADRESSE -->
						<div class="field is-grouped">
							<div class="control is-expanded has-icons-left">
								{{ form.street_number }}
								<span class="icon is-small is-left">
									<i class="fas fa-map-marker-alt"></i>
								</span>
							</div>
							<div class="control has-icons-left">
								<span class="select">
									{{ form.type_street }}
								</span>
								<span class="icon is-small is-left">
									<i class="fas fa-road"></i>
								</span>
							</div>
						</div>
						<div class="field">
							<div class="control">
								{{ form.street }}
							</div>
						</div>
						<div class="field is-grouped">
							<div class="control is-expanded">
								{{ form.postcode }}
							</div>
							<div class="control is-expanded">
								{{ form.city }}
							</div>
						</div>
						<div class="field">
							<div class="control has-icons-left">
								{{ form.country }}
								<span class="icon is-small is-left">
									<i class="fas fa-globe"></i>
								</span>
							</div>
						</div>
					</div>
					<div class="column">
						<!-- CARTE -->
						<div id="new-event-map" class="map"></div>
					</div>
				</div>
			</div>
			
			<!-- INVITATIONS -->
			<div class="step-content">

			</div>
			
			<!-- CRÉATION -->
			<div class="step-content has-text-centered">
				<h1 class="title is-4">Votre événement à bien été créé!</h1>
			</div>
		</div>

		<!-- ACTION -->
		<div class="steps-actions">
			<div class="steps-action">
				<a href="#" class="button" data-nav="previous">Retour</a>
			</div>
			<div class="steps-action">
				<a href="#" class="button" data-nav="next">Suivant</a>
			</div>
		</div>
	</div>
</form>
{% endblock account %}