events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('creation/', views.New_view, name='new'),
    path('<token>/modifier/', views.Change_view, name='change'),
    path('liste/', views.List_view, name='list'),
    path('<token>/', views.Detail_view, name='detail'),
    path('inscription/<token>/', views.Register_view, name='register'),
    path('inscription/<token>/<args>/', views.Register_view, name='register'),
    path('<token>/commentaire/', views.Comment_view, name="comment"),
    path('<token>/commentaire/edit/<int:comment_id>', views.Comment_Edit_view, name="edit"),
    path('<token>/commentaire/delete/<int:comment_id>', views.Delete_com_view, name="delete_com"),
    path('<token>/commentaire/like/<int:comment_id>', views.Like_com_view, name="like_com"),
    path('<token>/commentaire/dislike/<int:comment_id>', views.Dislike_com_view, name="dislike_com"),
    path('ajax/getsetevent/', views.getSetPos, name='setPos'),
    path('mes_event/<method>', views.my_event, name='my_event'),
    path('mes_event/all', views.my_event, name='my_event_vanilla'),
]

members/urls.py
from django.urls import path

from . import views

app_name = 'members'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('deconnexion/', views.logout_view, name='logout'),
    path('modifier/', views.change_view, name="change"),
    path('ajax/getnotif/', views.getNotif, name="getnotif"),
]

reunionou/urls.py
from django.contrib import admin
from django.urls import include, path
from index.views import e_handler404, e_handler500
 
handler404 = e_handler404
handler500 = e_handler500

urlpatterns = [
    path('accounts/', include('members.urls')),
    path('events/', include('events.urls')),
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="has-navbar-fixed-top">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>{% block title %}Reunionou{% endblock title %}</title>
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}"/>

        {% comment %} FONTS {% endcomment %}
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

        {% comment %} CSS {% endcomment %}
        {% block css %}
        {% endblock css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        {% comment %} NAVIGATION {% endcomment %}
        {% include "nav.html" %}

        {% comment %} CONTENT {% endcomment %}
        <section id="{% block page_name %}index{% endblock page_name %}" class="section">
            {% block content %}
            {% endblock content %}
        </section>
        
        {% comment %} FOOTER {% endcomment %}
        {% include "footer.html" %}

        {% comment %} SCRIPTS {% endcomment %}

        <!-- LEAFLET -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""></script>
        
        <!-- BULMA EXTENSIONS -->
        <script src="{% static 'bulma/sass/extensions/bulma-calendar/dist/js/bulma-calendar.min.js' %}"></script>
        <script src="{% static 'bulma/sass/extensions/bulma-steps/dist/js/bulma-steps.min.js' %}"></script>

        <!-- CUSTOM -->
        {% block js %}
        {% endblock js %}
        <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    </body>
</html>

templates/base_with_hero.html
{% load static %}

<!DOCTYPE html>
<html class="has-navbar-fixed-top">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>{% block title %}Reunionou{% endblock %}</title>
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}"/>

        {% comment %} FONTS {% endcomment %}
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
        
        {% comment %} CSS {% endcomment %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        {% comment %} NAVIGATION {% endcomment %}
        {% include "nav.html" %}
        {% comment %} HEADER {% endcomment %}
        {% include "header.html" %}

        {% comment %} CONTENT {% endcomment %}
        <section id="{% block page_name %}index{% endblock %}" class="section">
            {% block content %}
            {% endblock %}
        </section>
        
        {% comment %} FOOTER {% endcomment %}
        {% include "footer.html" %}

        {% comment %} SCRIPTS {% endcomment %}
        <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    </body>
</html>

templates/nav.html
{% load static %}

<nav class="navbar is-fixed-top {% if user.is_authenticated %}is-info{% else %}is-light{% endif %} has-shadow" role="navigation" aria-label="main navigation">
    <div class="container">
        <div class="navbar-brand">
            <a href="/" class="navbar-item">
                <img src="{% if user.is_authenticated %}{% static 'img/logo_white.png' %}{% else %}{% static 'img/logo.png' %}{% endif %}" alt="">
            </a>
    
            <a class="navbar-burger" role="button" aria-label="menu" aria-expanded="false" data-target="navbar-menu">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
    
        <div id="navbar-menu" class="navbar-menu">
            <div class="navbar-end">
                {% url 'index:home' as home %}
                <a href="{{ home }}" class="navbar-item {% if request.path == home %}is-active{% endif %}">
                    Accueil
                </a>
                <a href="{% url 'events:list' %}" class="navbar-item">
                    Liste des Evenements
                </a>
                {% if user.is_authenticated %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <a href="" class="navbar-link">
                        <span class="badge is-badge-small is-badge-danger" data-badge="1">Notifications</span>
                    </a>
    
                    <div class="navbar-dropdown is-right">
                        <a href="" class="navbar-item">
                            notification 1
                        </a>
                    </div>
                </div>
                {% endif %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        Compte
                    </a>
    
                    <div class="navbar-dropdown is-right">
                        {% if not user.is_authenticated %}
                        <a href="{% url 'index:login' %}" class="navbar-item">
                            Connexion
                        </a>
                        <hr class="navbar-divider">
                        <a href="{% url 'index:register' %}" class="navbar-item">
                            Inscription
                        </a>
                        {% else %}
                        <a href="{% url 'members:home' %}" class="navbar-item">
                            Dashboard
                        </a>
                        <a href="{% url 'members:profil' %}" class="navbar-item">
                            Profil
                        </a>
                        <hr class="navbar-divider">
                        <a href="{% url 'members:logout' %}" class="navbar-item">
                            Déconnexion
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>